### ISSUE TITLE
Error on downloading via smartphone.

### ISSUE THREAD

**Issue by cyber-cliff** [talmobi/bittysound#2]
Hi bro,

Can you help me to fix on downloading on smartphone? The process will start to down when it  downloads to phone. But when i tried to Teenysong.com it works perfectly.

Also the copy URL is not working but on your site it is working.

Please help bro.

Thanks,

**Comment by talmobi** [comment]
Hello,

This isn't really a publicly maintained project - just something I threw up on github for convenience. That being said I tried to simplify the app a bit and fixed playback bugs with the new version of chrome as well as a few other bugs.

The app didn't really require a db such as mongodb - I only made it so for fun/practice - so I switched it to a simplified json storage (see jsf library).

Good luck!

**Comment by cyber-cliff** [comment]
Hey Bro,

Ok bro i understand you, can you just share me your http://teenysong.com/ code? I know that is already working. Please bro.

Thanks,

**Comment by cyber-cliff** [comment]
Ok i tried you latest push code and it works now with smartphone. It can download via smartphone. 

But still the Copy of URL/LINK of the song still not working.

**Comment by talmobi** [comment]
Try https://clipboardjs.com/
